export const actions = {
    SET_PLACEMARKS: 'SET_PLACEMARKS',
    GET_PLACEMARKS_ERROR: 'GET_PLACEMARKS_ERROR',
    ADD_PLACEMARK: 'ADD_PLACEMARK',
    CLOSE_ITEM_CARD: 'CLOSE_ITEM_CARD'
};

export const urls = {
    GET_PLACEMARKS_URL: 'something'
};